name: AMD Stock Update

on:
  schedule:
    - cron: '30 21 * * 1-5'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install yfinance
    - name: Get AMD Data
      run: |
        cat > get_amd.py << 'EOF'
        import yfinance as yf
        data = yf.download("AMD", period="5d", progress=False)
        data.to_csv("amd_stock_data.csv")
        print("Done")
        EOF
        python get_amd.py
    - name: Push
      run: |
        git config user.name "Actions"
        git config user.email "actions@github.com"
        git add -A
        git commit -m "Update $(date +'%Y-%m-%d')" || true
        git push || true
