name: AMD Stock Data Extraction

on:
  schedule:
    - cron: '30 21 * * 1-5'
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: pip install yfinance
    
    - name: Extract AMD data
      run: |
        python << 'EOF'
        import yfinance as yf
        from datetime import datetime
        
        # Descargar datos de AMD
        data = yf.download("AMD", period="1d", progress=False)
        
        # Guardar en CSV
        data.to_csv('amd_stock_data.csv')
        print(f"Datos guardados. Último precio: ${data['Close'].iloc[-1]:.2f}")
        EOF
    
    - name: Commit and push
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add amd_stock_data.csv || echo "No file to add"
        git commit -m "Update AMD data $(date +%Y-%m-%d)" || echo "No changes"
        git push || echo "No changes to push"
