name: Daily AMD Stock Data Extraction

on:
  schedule:
    # Ejecutar a las 21:30 UTC (16:30 EST después del cierre del mercado)
    - cron: '30 21 * * 1-5'  # Lunes a Viernes
  workflow_dispatch:  # Permite ejecución manual

jobs:
  extract-stock-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache dependencias
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Crear directorio data si no existe
      run: mkdir -p data
    
    - name: Ejecutar extractor
      run: python amd_stock_extractor.py
    
    - name: Verificar archivos generados
      run: |
        echo "Contenido del directorio data:"
        ls -la data/ || echo "No hay archivos en data/"
        echo "Contenido del directorio raíz:"
        ls -la
    
    - name: Commit y Push cambios
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Action"
        git add data/ || echo "No hay archivos para agregar en data/"
        git add . || echo "No hay archivos para agregar"
        if git diff --quiet && git diff --staged --quiet; then
          echo "No hay cambios para commit"
        else
          git commit -m "📊 Actualización diaria de datos AMD - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        fi
