name: AMD Stock Data Extractor

on:
  schedule:
    - cron: "15 20 * * 1-5"  # Lunes a viernes a las 20:15 UTC (16:15 ET)
  workflow_dispatch:

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run data extraction script
        run: |
          python stock_data_extractor.py
          
      - name: Check if CSV exists
        id: check_csv
        run: |
          if [ -f "amd_stock_data.csv" ]; then
            echo "csv_exists=true" >> $GITHUB_ENV
          else
            echo "csv_exists=false" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.csv_exists == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add amd_stock_data.csv
          git commit -m "Update AMD data $(date +%Y-%m-%d)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
